from django.conf.urls.defaults import *

urlpatterns = patterns('',
	#url(r'^comments/$',
	#	view	= 'photos.views.gallery_comments',
	#	name	= 'photo_gallery_comment',
	#),
	url(r'^galleries/$',
		view	= 'photos.views.gallery_archive',
		name	= 'photo_gallery_archive',
	),
	#url(r'^(?P<gallery_slug>[-\w]+)/gallery/(?P<photo_slug>[-\w]+)/$',
	#	view	= 'photos.views.gallery_photo_detail',
	#	name	= 'photo_gallery_photo_detail',
	#),
	url(r'^(?P<gallery_slug>[-\w]+)/gallery/$',
		view	= 'photos.views.gallery_detail',
		name	= 'photo_gallery_detail',
	),
	url(r'^(?P<gallery_slug>[-\w]+)/$',
		view	= 'photos.views.gallery_title',
		name	= 'photo_gallery_title',
	),
	url(r'^$', 
		view	= 'photos.views.gallery_index',
		name	= 'photo_gallery_index',
	),
)